### ISSUE TITLE
More in-depth guide please

### ISSUE THREAD

**Issue by Anazark** [Bugaddr/android_debloater_scripts#1]
Hello thank you for your script
Unfortunately i'm not a developer and my knowledge is really limited, could you explain to me how i should use this script ?

I'm on linux. Should i just plug my phone, activate usb debugging, and double-click the .sh file and that's it ?

Thanks

**Comment by Bugaddr** [comment]
> Hello thank you for your script Unfortunately i'm not a developer and my knowledge is really limited, could you explain to me how i should use this script ?
> 
> I'm on linux. Should i just plug my phone, activate usb debugging, and double-click the .sh file and that's it ?
> 
> Thanks

Hello, its pretty easy
1. Install adb tools on your distro and reboot
2. activate USB debugging on phone
3. connect phone
4. execute the script from terminal as `./debloat.sh 1` (here 1 is user id, don't change it )

**Comment by Anazark** [comment]
Thank's, it sounds fairly simple
Maybe you should add it to the description in the main page, so that it could help others like me ? :+1: 
Thanks again !

**Comment by Bugaddr** [comment]
> Thank's, it sounds fairly simple Maybe you should add it to the description in the main page, so that it could help others like me ? 👍 Thanks again !

Thanks for suggestion, will do that :+1:

**Comment by Bugaddr** [comment]
Am closing this as fixed, Thanks !!
